#!/usr/bin/env python3
"""
Bundle shakar_ref into a single Python file for Pyodide.

This creates a self-extracting module bundle that registers all shakar_ref
modules in sys.modules when executed.

Usage:
    python bundle.py > shakar_bundle.py
"""

from pathlib import Path
import base64
import zipfile
import io


def create_bundle():
    src_dir = Path(__file__).parent.parent / "src"

    # Files to exclude (tests, dev utilities)
    exclude_patterns = {"test_", "updater"}

    # Create in-memory zip
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add all Python files from shakar_ref
        shakar_ref = src_dir / "shakar_ref"
        for py_file in sorted(shakar_ref.rglob("*.py")):
            # Skip test/dev files
            if any(pat in py_file.name for pat in exclude_patterns):
                continue
            arcname = str(py_file.relative_to(src_dir))
            info = zipfile.ZipInfo(arcname, date_time=(2000, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, py_file.read_text(encoding="utf-8"))

    # Base64 encode
    zip_data = base64.b64encode(zip_buffer.getvalue()).decode("ascii")

    # Generate the bundle loader with import hook
    bundle = f'''"""
Shakar reference implementation - bundled for Pyodide.
Auto-generated by web/bundle.py - do not edit.
"""

import sys
import base64
import zipfile
import io
import types
from importlib.abc import MetaPathFinder, Loader
from importlib.machinery import ModuleSpec

_BUNDLE_DATA = """{zip_data}"""


class _BundleLoader(Loader):
    def __init__(self, source, is_package=False):
        self.source = source
        self.is_package = is_package

    def create_module(self, spec):
        return None  # Use default module creation

    def exec_module(self, module):
        module.__file__ = module.__name__.replace(".", "/") + ".py"
        if self.is_package:
            module.__path__ = []
        exec(compile(self.source, module.__file__, "exec"), module.__dict__)


class _BundleFinder(MetaPathFinder):
    def __init__(self, modules):
        self.modules = modules

    def find_spec(self, fullname, path, target=None):
        # Check for package (__init__)
        init_name = fullname + ".__init__"
        if init_name in self.modules:
            return ModuleSpec(
                fullname,
                _BundleLoader(self.modules[init_name], is_package=True),
                is_package=True,
            )

        # Check for regular module
        if fullname in self.modules:
            return ModuleSpec(
                fullname,
                _BundleLoader(self.modules[fullname], is_package=False),
                is_package=False,
            )

        return None


def _install_bundle():
    zip_bytes = base64.b64decode(_BUNDLE_DATA)
    zf = zipfile.ZipFile(io.BytesIO(zip_bytes), "r")

    # Extract all modules
    modules = {{}}
    for name in zf.namelist():
        if name.endswith(".py"):
            content = zf.read(name).decode("utf-8")
            # Convert path to module name
            mod_name = name[:-3].replace("/", ".")
            modules[mod_name] = content

    # Install the finder
    sys.meta_path.insert(0, _BundleFinder(modules))


_install_bundle()

# Export the run function for easy access
from shakar_ref.runner import run as shk_run
from shakar_ref.runner import run_with_env, eval_in_env
'''

    return bundle


if __name__ == "__main__":
    print(create_bundle())
